name: Validate on PR
on: 
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - 'main'
      - 'develop'
      - 'release/'
      - 'hotfix/'
      - 'feature/'
      - 'bugfix/'
    paths:
      - 'force-app/**'
jobs:
  Validate:
    runs-on: ubuntu-latest # Runs the job on the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches full git history to enable accurate diffing of file changes

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli # Installs the Salesforce CLI globally using npm

      - name: Authenticate to Salesforce (JWT)
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key # Saves the JWT key from secrets into a file
          sf org login jwt \ # Logs into Salesforce using JWT-based authentication
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \ # Client ID of the connected app
            --jwt-key-file server.key \ # Path to the JWT key file
            --username ${{ secrets.SF_USERNAME }} \ # Salesforce username to authenticate
            --instance-url ${{ secrets.SF_SERVER_URL }} \ # Salesforce instance URL
            --alias SFDC_v1 \ # Assigns an alias to the authenticated org
            --set-default # Sets this org as the default for subsequent CLI commands

      - name: Debug Git Log
        run: |
          echo "Last 5 commits:" # Prints message header
          git log --oneline -5 # Displays the last 5 commits in a concise format

      - name: Validate the changes mentioned in package
        id: changes
        run: |
          sf project deploy validate --manifest manifest/package.xml
  
      
  

